language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - "linux"
  - "osx"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install unittest2; fi
  - python setup.py install

script:
  - make flakes
  - make test

after_success:
  - make coveralls

notifications:
  email:
    on_success: change
    on_failure: change
