language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

matrix:
  include:
    - python: "2.7"
      env: TMODE=flake8
env:
    TMODE=tests

install:
  - pip install pytest
  - "if [[ $TMODE == 'test' ]]; pip install pytest; fi"
  - "if [[ $TMODE == 'test' ]]; python setup.py install; fi"

script:
  - python setup.py $TMODE
  - "if [[ $TMODE == 'test' ]]; python setup.py sdist --formats zip,gztar bdist_wheel; fi"

after_success:
  - "if [[ $TMODE == 'test' ]]; coveralls; fi"

notifications:
  email:
    on_success: change
    on_failure: change
